version: '2.4'

services:
  api:
    build: .
    ports:
      - "3000:3000"             # web
      - "3001:3001"             # nREPL
    volumes:
      - .:/usr/src/app
      - ./m2:/root/.m2
    environment:
      - API_ROOT=/api
      - FRONTEND_ROOT=/web
      - DB_NAME=upgraded_winner
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PASSWORD=1234
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
  react:
    build: "./upgraded-winner-frontend/"
    ports:
      - "3003:3000"
    volumes:
      - './upgraded-winner-frontend:/app'
    environment:
          - CHOKIDAR_USEPOLLING=true
          - PUBLIC_URL=web
          - REACT_APP_API_ROOT=/api
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './host.key:/etc/nginx/localhost.key'
      - './host.cert:/etc/nginx/localhost.cert'
    ports:
      - 8080:8080
      - 443:443

# networks:
#   default:
#     driver: host
