version: '2.4'

services:
  app:
    build: .
    ports:
      - "3000:3000"             # web
      - "3001:3001"             # nREPL
    volumes:
      - .:/usr/src/app
      - ./m2:/root/.m2
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
# networks:
#   default:
#     driver: host
